version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty321
      POSTGRES_DB: practice
    ports:
      - "5435:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data